name: Robot Framework

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
      run: |
        docker build -t docker-robotframework .
    - name: Run image
      run: |
        docker run --rm -v $(pwd)/tests:/tests/ -ti kriffx/example
    - name: Reports
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: ./
