name: Robot Framework

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: How To Build Image
      run: |
        docker build -t docker-robotframework .
    - name: Run The Image
      run: |
        docker images
        docker run --name docker-robotframework -d -v $(pwd)/tests:/tests/ -ti docker-robotframework
    - name: Run the robot command
      run: |
        docker exec docker-robotframework robot --listener KitsuListener.py -d reports tests/
    - name: Reports
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: ./
